# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python_data_analysis_notes',
                'doc_host': 'https://dmitryhits.github.io',
                'git_url': 'https://github.com/dmitryhits/python_data_analysis_notes',
                'lib_path': 'python_data_analysis_notes'},
  'syms': { 'python_data_analysis_notes.core': { 'python_data_analysis_notes.core.foo': ( 'core.html#foo',
                                                                                          'python_data_analysis_notes/core.py')}}}
